# Generated by Django 3.2.4 on 2021-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzeria_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=400)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.IntegerField(blank=True, default=0)),
                ('website', models.URLField(max_length=420, null=True)),
                ('logo_image', models.ImageField(blank=True, default='pizzaimages/default.jpg', upload_to='pizzaimages')),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
